# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_passworde: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["258d0a0b59b5b0ad1444f54dc14e1e53-us9"] %>
  mailchimp_list_idy: <%= ENV["vistors"] %>
  domain_name: example.com
  owner_email: <%= ENV["byron.johnson@gmail.com"] %>
  secret_key_base: f7d13c5f85508ffe75b89a3efefcfffa989d03e65f53bfc73f075f549cbfa2be347ccbe131220b0b1e568bd73f46d6ae78425efc1da96866d194db3d3b3cee4a


test:
  secret_key_base: 07865033be223f83848025314c6aa5f9b2ad0d41a53e6c8f234e4f38ed8f6eb4927fa29bca24958a840f762ed1269a0537b99cdf1e1c881cce7405c44676bfe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_passworde: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["258d0a0b59b5b0ad1444f54dc14e1e53-us9"] %>
  mailchimp_list_idy: <%= ENV["vistors"] %>
  domain_name: <%= ENV["example.com"] %>
  owner_email: <%= ENV["byron.johnson@gmail.com"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
